### ISSUE TITLE
Commandline issues

### ISSUE THREAD

**Issue by The-E** [G-Node/gin-cli#128]
While testing the current dev build (`GIN command line client 0.12dev Build 000626 (ce6bfcab8e6b6ac640c9f13190fd566fcdfd75cf)` as per `gin --version`), I've seen a bit of unwanted behaviour.

1. `gin remove-content <filename>` on a file returns 
```
Nothing to do
Removing content gin-cli-0.6-windows-386.zip [32mOK[0m
  [31mError[0m: unexpected end of JSON input

[31mERROR [0m1 operation failed
```
2. `gin ls -json` hangs indefinitely
3. `gin remove-content` exhibits strange behaviour. I have a checkout of the gin-cli-builds repository.
The file `gin-cli-0.11-windows-386.zip` is present on disk. When I navigate to that directory and issue the command `gin remove-content gin-cli-0.10-windows-386.zip`, I would expect an error to occur (like, "No file with that name found" or something.) Instead, `gin-cli-0.11-windows-386.zip` is removed, with the same output as mentioned in 1. Complete cmdline output:
```
PS C:\Users\fwoltermann\Desktop\gin-cli-builds\v0.11> gin.exe remove-content gin-cli-0.10-windows-386.zip
Nothing to do
Removing content gin-cli-0.11-windows-386.zip [32mOK[0m
  [31mError[0m: unexpected end of JSON input

[31mERROR [0m1 operation failed
```

**Comment by The-E** [comment]
BUT WAIT, THERE'S MORE
```
PS C:\Users\fwoltermann\Desktop\gin-cli-builds\v0.11> gin.exe get-content .\gin-cli-0.6-windows-386.zip
Downloading gin-cli-0.11-linux-amd64.tar.gz [32mOK[0m (5.49MB/s)
Downloading gin-cli-0.11-macos-amd64.tar.gz [32mOK[0m (5.51MB/s)
Downloading gin-cli-0.11-macos-bundle.dmg [32mOK[0m (5.95MB/s)
Downloading gin-cli-0.11-windows-386.zip [32mOK[0m (5.97MB/s)
Downloading gin-cli-0.11.deb [32mOK[0m (5.92MB/s)
```

This seems ... unwise

**Comment by achilleas-k** [comment]
There was a bug where the ExpandGlobs function would return an empty array if it failed to match anything. Then this empty array would be passed to whatever function was being called and essentially the git or git-annex command would be run without arguments, which usually means "everything" or "everything under current dir". 

I noticed this yesterday while working on some other issues and I fixed it so that ExpandGlobs returns an error if the file argument doesn't match (see 6d09094418f917e948079233dd1fedf4917c7277).

I'll upload a new dev build that includes this fix now so let me know if it works.

**Comment by achilleas-k** [comment]
Ok, I'm pretty sure every one of these should be addressed by the upcoming PR. Commit 8afe6f3c638c6377eafb642799b1ebabb384ec87 is where it's at now if you wanna try it. It's currently available on gin-cli-builds as well.

**Comment by The-E** [comment]
I'll check it later today

**Comment by The-E** [comment]
Found another issue regarding gin ls.

Steps to reproduce:
1. Create a new repository (i.e. gin create reponame)
2. Run gin ls -> No output, or `null` with gin ls --json
3. Copy a new file into the repository
4. Run gin ls
Expected output: A listing of files with the new file listed as untracked
Received output: `ERROR unexpected end of JSON input`

**Comment by The-E** [comment]
I should add: returning `null` in an empty repository is no problem, I can account for that.

**Comment by The-E** [comment]
FURTHERMORE:
1. Have a gin repository checkout.
2. Add files to that directory
3. run `gin ls`
Received output: `ERROR unexpected end of JSON input`

**Comment by achilleas-k** [comment]
So this occurred because git-annex *sometimes* outputs blank lines at the end of its line-by-line JSON output. The client was trying to unmarshal empty lines, hence the message.

I didn't catch this sooner because it doesn't seem to occur on Linux, at least not with the version I have installed here.

The fix is easy: I just trim each line and check if it's empty before unmarshalling.

**Comment by achilleas-k** [comment]
These issues should be long fixed now.
