### ISSUE TITLE
GinClientApp error at startup: Can't install the Dokan driver

### ISSUE THREAD

**Issue by vncntprvst** [G-Node/gin-cli#318]
Hi,
I installed the GIN client WinGIN (on Windows 10). The app runs and works (although it fails when uploading too many new files), but I get this error when it starts: 

![image](https://user-images.githubusercontent.com/1872756/191830325-6d45c7b6-7a08-466c-9867-d9df8a3887e3.png)

Any idea how to fix it, short of re-installing it ?
Thanks

**Comment by mpsonntag** [comment]
Hi @vncntprvst, thank you for reporting the issue. I am not that familiar with WinGIN, but I think the issue lies with an incompatibility of installed Dokan drivers with the Dokan environment supplied by the WinGIN installer.

There are some related issues on the WinGIN repository, maybe this will already help: [Specify list of supported Dokan app versions](https://github.com/G-Node/WinGIN/issues/160), [windows 7 and dokan](https://github.com/G-Node/WinGIN/issues/158).

In general I think it is an issue with the WinGIN installer rather than the gin client. I opened an issue over at the WinGIN repository and will close the issue here.
