### ISSUE TITLE
"gin upload" vs "gin upload ."

### ISSUE THREAD

**Issue by ajkswamy** [G-Node/gin-cli#98]
Hi

I am using the following protocol to update an existing gin repository:

1. make changes/add files
2. use git to stage and commit the changes
3. upload it to gin using the gin-cli

when uploading, I get the following error when I use "gin upload .":

    Uploading...Error adding files to repository.

However, using "gin upload" results in:`

    No files specified for upload. Synchronising metadata.
    To upload all files under the current directory, use:

	gin upload .

    Uploading...done!

When I check the on line repository after "gin upload", all the files are shown to have been uploaded.

What is the difference between "gin upload" and "gin upload ."? When should I use one over another?

Sincerely
Ajay

**Comment by achilleas-k** [comment]
Hey Ajay!

The difference between `gin upload .` and `gin upload` is that the dot forces an upload of everything under the current directory while without any path or file argument it simply pushes metadata changes.

A better way to understand the difference is with what gin does under the hood.

`gin upload` is similar to performing a `git push`. In reality in uses `git annex sync`, but the idea is the same.

`gin upload .` is similar to performing `git commit .` followed by `git push`.

More generally, `gin upload filename.ext` will add and commit changes that were made to `filename.ext` and then perform a push (which will also upload any other committed yet unpushed changes). In the case of the path being `.`, it just goes ahead and adds everything under the current working directory. With no argument, it adds nothing, but still performs a `git push` in order to synchronise metadata and previously committed (yet unpushed) changes with the remote.

In your specific case, since you `git add` and `git commit` before performing a `gin upload`, the changes you committed are pushed to the remote.

Now there is one small issue: Why does `gin upload .` fail with an error? To be honest, I'm not entirely sure. It might have to do with the gin client attempting to automatically add files to the annex that have already been added to git proper. Could you send me the gin client log file so I can have a look at what went wrong? You can find it at `~/.local/share/gin/gin.log`.

**Comment by dEvasEnApati** [comment]
Thanks Achilleas! That clears things up. To confirm, `gin upload .` can be used to commit all changes in a single shot with default commit message and push that commit, while `git add ...; git commit .... gin upload` can be used for finer control of commit content and message?

Here is the log file: [gin.log](https://github.com/G-Node/gin-cli/files/1278372/gin.log.txt)

**Comment by achilleas-k** [comment]
> Thanks Achilleas! That clears things up. To confirm, gin upload . can be used to commit all changes in a single shot with default commit message and push that commit, while git add ...; git commit .... gin upload can be used for finer control of commit content and message?

Yes.

Thanks for the log file. The error is certainly a bug. The client shouldn't throw out errors even if the user made manual commits and then tried to `gin upload .`.
